language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=29

services:
  - mysql
  
matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -n
  - php bin/phpunit

script:
  - 
  # this checks that the source code follows the Symfony Code Syntax rules
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || php ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  # this checks that the YAML config files contain no syntax errors
  - php bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - php bin/console lint:twig templates
  # this checks that the XLIFF translations contain no syntax errors
  - php bin/console lint:xliff translations
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - php bin/console security:check
  # this checks that Doctrine's mapping configurations are valid
  - php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
