# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: flouch/symfony4-image-docker 
pipelines:
  branches:
    production:
      - step:
    # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
    # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
          name: Deploy to Heroku
          deployment: test   # set to test, staging or production
    # trigger: manual  # uncomment to have a manual step
          script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

    master:
    - step:
        name: Build & test
        caches:
          - composer
          - bundle
        script:
          - composer install
          - php bin/console doctrine:schema:update --force
          - php bin/console doctrine:fixtures:load -n
          - vendor/bin/phpunit

        services: 
          - mysql            
definitions: 
  services: 
    mysql: 
      image: mysql:5.7  
      environment: 
        MYSQL_DATABASE: 'azerty'
        MYSQL_ROOT_PASSWORD: '123456'
  caches:
    bundle: vendor